protected/models/Trade.php
<?php

/**
 * This is the model class for table "trade".
 *
 * The followings are the available columns in table 'trade':
 * @property string $id
 * @property integer $asset_id
 * @property string $user_id
 * @property integer $status
 * @property integer $last_trade_id
 * @property integer $next_trade_id
 * @property string $init_date
 * @property string $mail_date
 * @property string $receive_date
 * @property string $ready_date
 * @property string $finish_date
 *
 * The followings are the available model relations:
 * @property Asset $asset
 * @property User $user
 * @property UserQueue[] $userQueues
 */
class Trade extends CActiveRecord
{
    const STATUS_WAITING_FOR_MAILING    = 0;
    const STATUS_IN_TRANSIT             = 1;
    const STATUS_RECEIVED               = 2;
    const STATUS_READY_FOR_NEXT_MAILING = 3;
    const STATUS_FINISHED               = 4;
	/**
	 * Returns the static model of the specified AR class.
	 * @return Trade the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'trade';
	}
	
	public function findGamesToSend($user_id) {
	    return $this->findAll(
	      array(
	        'alias' => 'asset',
	        'condition' => 'status='.self::STATUS_WAITING_FOR_MAILING.' and last_user_id=:user_id',	        	
            'params' => array(':user_id'=>$user_id)));
	}

	public function findGamesToAck($user_id) {
	    return $this->findAll(
	      array(
	        'alias' => 'asset',
	        'condition' => 'status='.self::STATUS_IN_TRANSIT.' and user_id=:user_id',	        	
            'params' => array(':user_id'=>$user_id)));
	}	
	
	public function findGamesReceived($user_id) {
	  	return $this->findAll(
	      array(
	        'alias' => 'asset',
	        'condition' => 'status in ('.self::STATUS_RECEIVED.','.self::STATUS_READY_FOR_NEXT_MAILING.') and user_id=:user_id',	        	
            'params' => array(':user_id'=>$user_id)));
	}
	
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('asset_id, user_id, status, init_date', 'required'),
			array('asset_id, status, last_trade_id, next_trade_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>11),
			array('mail_date, receive_date, ready_date, finish_date', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, asset_id, user_id, status, last_trade_id, next_trade_id, init_date, mail_date, receive_date, ready_date, finish_date', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'asset' => array(self::BELONGS_TO, 'Asset', 'asset_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'last_user' => array(self::BELONGS_TO, 'User', 'last_user_id'),		
			'userQueues' => array(self::HAS_MANY, 'UserQueue', 'trade_id'),
		    'next_trade' => array(self::HAS_ONE, 'Trade', 'next_trade_id'),
		    'last_trade' => array(self::HAS_ONE, 'Trade', 'last_trade_id')
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'asset_id' => 'Asset',
			'user_id' => 'User',
			'status' => 'Status',
			'last_trade_id' => 'Last Trade',
			'next_trade_id' => 'Next Trade',
			'init_date' => 'Init Date',
			'mail_date' => 'Mail Date',
			'receive_date' => 'Receive Date',
			'ready_date' => 'Ready Date',
			'finish_date' => 'Finish Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('asset_id',$this->asset_id);
		$criteria->compare('user_id',$this->user_id,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('last_trade_id',$this->last_trade_id);
		$criteria->compare('next_trade_id',$this->next_trade_id);
		$criteria->compare('init_date',$this->init_date,true);
		$criteria->compare('mail_date',$this->mail_date,true);
		$criteria->compare('receive_date',$this->receive_date,true);
		$criteria->compare('ready_date',$this->ready_date,true);
		$criteria->compare('finish_date',$this->finish_date,true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/TradeController.php
<?php

class TradeController extends Controller
{
	public function actionIndex()
	{
       $user_id = Yii::app()->user->id;
       
       $model = Trade::model();
       
	   $this->render('index',array(
	     'gamesToSend' => $model->findGamesToSend($user_id),
	     'gamesToAck'  => $model->findGamesToAck($user_id),
	     'gamesReceived' => $model->findGamesReceived($user_id)
	   ));
	}
	
	public function actionUpdate($trade_id)
	{
       $user_id = Yii::app()->user->id;
	  
       $trade = $this->loadTrade($trade_id);

       switch($trade->status) {
         case Trade::STATUS_WAITING_FOR_MAILING:
            if(isset($_POST['Trade']['mail_date'])) {
              $trade->mail_date = $_POST['Trade']['mail_date'];
              $trade->status = Trade::STATUS_IN_TRANSIT;
              if($trade->save())
                $this->redirect(array('trade/index')); 
            } else
              $trade->mail_date = strftime('%Y-%m-%d');
            $this->render('update_mail',array('trade'=>$trade));
            break;         
         case Trade::STATUS_IN_TRANSIT:
            if(isset($_POST['Trade']['receive_date'])) {
              $trade->receive_date = $_POST['Trade']['receive_date'];
              $trade->status = Trade::STATUS_RECEIVED;
              if($trade->save())
                $this->redirect(array('trade/index')); 
            } else
              $trade->receive_date = strftime('%Y-%m-%d');
            $this->render('update_transit',array('trade'=>$trade));
            break;         
         case Trade::STATUS_RECEIVED:
            if(isset($_POST['ready'])) {
              $trade->ready_date = strftime('%Y-%m-%d');
              $trade->status = Trade::STATUS_READY_FOR_NEXT_MAILING;
              if($trade->save())
                $this->redirect(array('trade/index')); 
              
            }
            $this->render('update_received',array('trade'=>$trade));
            break;               
         default:
             throw new CHttpException(404,'The requested page does not exist.');         
       }       
	}

    public function loadTrade($id) {
      $model=Trade::model()->findByPk((int)$id);
      if($model===null)
      throw new CHttpException(404,'The requested page does not exist.');
      return $model;
	}
	
  /**
   * @return array action filters
   */
  public function filters()
  {
    return array(
			'accessControl', // perform access control for CRUD operations
    );
  }

  /**
   * Specifies the access control rules.
   * This method is used by the 'accessControl' filter.
   * @return array access control rules
   */
  public function accessRules()
  {
    return array(
    array('allow',
    			'actions'=>array('index','update'),
    			'users'=>array('@'),
    ),
        array('deny',  // deny all users
				'users'=>array('*'),
    ),
    );
  }
}

protected/views/trade/_asset.php
<h4><?php echo $trade->asset->title->name ?></h4>

<?php if($trade->status == Trade::STATUS_WAITING_FOR_MAILING): ?>
<em>Send to:</em><br/>
<p>
<?php echo $trade->user->getFormattedAddress(); ?>
</p>
<?php elseif($trade->status == Trade::STATUS_IN_TRANSIT): ?>
<em>Mailed to you on :</em> <?php echo $trade->mail_date ?>
<?php elseif($trade->status == Trade::STATUS_RECEIVED || $trade->status == TRADE::STATUS_READY_FOR_NEXT_MAILING): ?>
<em>Date received :</em> <?php echo $trade->receive_date ?><br/>
<em>Ready to return : </em> <?php echo $trade->status == TRADE::STATUS_READY_FOR_NEXT_MAILING ? 'Yes' : 'No' ?>
<?php endif; ?>

<br/>

<?php if($trade->status != TRADE::STATUS_READY_FOR_NEXT_MAILING): ?>
<?php echo CHtml::link('Update Status', array('trade/update','trade_id'=>$trade->id)); ?>
<?php endif; ?>

<br/>

protected/views/trade/index.php
<?php
$this->breadcrumbs=array(
	'Trade',
);?>

<h1>Games to send:</h1>

<?php
if(empty($gamesToSend))
  echo "None";
else
  foreach($gamesToSend as $trade)
	  $this->renderPartial('_asset',
			array('trade'=>$trade));
?>

<br/><h1>Games to acknowledge receipt:</h1>

<?php
if(empty($gamesToAck))
  echo "None";
else
  foreach($gamesToAck as $trade)
	  $this->renderPartial('_asset',
			array('trade'=>$trade));
?>

<br/><br/><h1>Games borrowed:</h1>

<?php
if(empty($gamesReceived))
  echo "None";
else
  foreach($gamesReceived as $trade)
	  $this->renderPartial('_asset',
			array('trade'=>$trade));
?>

protected/views/trade/update_mail.php
<h1>Update Trade</h1>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'trade-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php echo $form->errorSummary($trade); ?>

<label>Enter the date you have mail the game below:</label><br/><br/>

<div class="row">
	<?php echo $form->labelEx($trade,'mail_date'); ?>
	<?php echo $form->textField($trade,'mail_date',array('size'=>15,'maxlength'=>15)); ?>
	<?php echo $form->error($trade,'mail_date'); ?>
</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Update'); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/trade/update_received.php
<h1>Update Trade</h1>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'trade-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php echo $form->errorSummary($trade); ?>

<label>Do you wish to make this game as ready to return?</label><br/><br/>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Mark Ready',array('name'=>'ready')); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/trade/update_transit.php
<h1>Update Trade</h1>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'trade-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php echo $form->errorSummary($trade); ?>

<label>Enter the date you received the game below:</label><br/><br/>

<div class="row">
	<?php echo $form->labelEx($trade,'receive_date'); ?>
	<?php echo $form->textField($trade,'receive_date',array('size'=>15,'maxlength'=>15)); ?>
	<?php echo $form->error($trade,'receive_date'); ?>
</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Update'); ?>
	</div>

<?php $this->endWidget(); ?>