protected/controllers/FriendsController.php
<?php

class FriendsController extends Controller
{
	
	public function actionRequest($username = null) {
		if($username) {
			$user = User::model()->findByUsername($username);
			if(!$user)
				Yii::app()->user->setFlash('error',"The username '$username' was not found.");
			else {
				list($result,$msg) = UserHelper::processFriendRequest(User::current(),$user);
								
				Yii::app()->user->setFlash($result,$msg);
				if($result == 'success') $username = '';
			}
		}

		$this->render('request',array('username'=>$username));		
	}
	
	public function actionApprove($username = null,$status = null) {
		
		if($username && $status) {
			$user = User::model()->findByUsername($username);
			if(!$user)
				Yii::app()->user->setFlash('error',"The username '$username' was not found.");
			else {
				list($result,$msg) = UserHelper::processFriendRequestResponse(User::current(),$user,$status);
								
				Yii::app()->user->setFlash($result,$msg);
				$this->redirect(array('approve'));
			}
		}		
		
		$users = User::model()->findAll(array(
			'condition'=>'l.status=:status and l.link_type=:type and l.second_user_id=:user',
			'join'=>'inner join user_link l on t.id=l.first_user_id',
			'params'=>array(':status'=>UserLink::STATUS_REQUESTED,':type'=>UserLink::TYPE_FRIEND,':user'=>Yii::app()->user->id)));

		$this->render('approve',array('users'=>$users));		
	}
	
  public function loadUserModel($id)
  {
    $model=User::model()->findByPk((int)$id);
    if($model===null)
    throw new CHttpException(404,'The requested page does not exist.');
    return $model;
  }
	

	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('UserLink', array(
      	'criteria' => array(
          'condition'=>'first_user_id=:user and status=:status and link_type=:type',
	  'params'=>array(':user'=>Yii::app()->user->id,':status'=>UserLink::STATUS_CONFIRMED,':type'=>UserLink::TYPE_FRIEND))));

         $this->render('index',array(
			'dataProvider'=>$dataProvider,
      ));
        
        
	}

	public function actionRemove($link_id)
	{
		$user_link = $this->loadUserLinkModel($link_id)->delete();
	    
	    $this->redirect('index');
	}
  public function loadUserLinkModel($id)
  {
    $model=UserLink::model()->findByPk((int)$id);
    if($model===null)
    throw new CHttpException(404,'The requested page does not exist.');
    return $model;
  }
	
	
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	public function accessRules()
	{
		return array(
			array('allow',
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

}

protected/views/friends/_request.php
<form method="get" action="<?php echo $this->createUrl('friends/request'); ?>">
    <?php echo CHtml::label('Username','username'); ?>
    <?php echo CHtml::textField('username',$username); ?>
    <?php echo CHtml::submitButton('Submit'); ?>    
</form>

protected/views/friends/approve.php
<?php
$this->breadcrumbs=array(
	'Friend Requests',
);?>


	<h1>Friend Requests</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider'=>new CArrayDataProvider($users),
    'columns'=>array(
    array(
        'class'=>'CLinkColumn',
        'header'=>'From User',
        'labelExpression'=>'$data->username',
        'urlExpression'=>"Yii::app()->createUrl('user/view',array('username'=>\$data->username))",
    ),
    array(
        'class'=>'CLinkColumn',
        'header'=>'Approve',
        'label'=>'Approve',
        'urlExpression'=>"Yii::app()->createUrl('friends/approve',array('username'=>\$data->username,'status'=>'approve'))",
    ),
    array(
        'class'=>'CLinkColumn',
        'header'=>'Reject',
        'label'=>'Reject',
        'urlExpression'=>"Yii::app()->createUrl('friends/approve',array('username'=>\$data->username,'status'=>'reject'))",
    )))); ?>



protected/views/friends/index.php
<?php
$this->breadcrumbs=array(
	'Friends',
);?>



	<h1>My Friends</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
    'columns'=>
	array(
      'second_user.name',
    array(
    'class'=>'CLinkColumn',
    'header'=>'Actions',
    'labelExpression'=>'"Remove"',
    'urlExpression'=>'Yii::app()->createUrl("friends/remove",array("link_id"=>$data->id))',
	),
		array(
    	'class'=>'CLinkColumn',
   		'header'=>'Actions',
    	'labelExpression'=>'"View Library"',
    	'urlExpression'=>'Yii::app()->createUrl("library/index",array("user_id"=>$data->second_user->id))'
	),

))); ?>

<h3>Send Friend Request</h3>

<?php echo $this->renderPartial('_request',array('username'=>'')); ?>

protected/views/friends/request.php
<h3>Send Friend Request</h3>

<?php echo $this->renderPartial('_request',array('username'=>$username)); ?>